#!/usr/bin/env sh

# Check if nvm exists and load it
if [ -s "$HOME/.nvm/nvm.sh" ]; then
  . "$HOME/.nvm/nvm.sh"  # Load nvm
  nvm use --lts  # Use LTS version
fi

npx lint-staged --config ./lint-staged.config.js
npx vitest run --silent --passWithNoTests